name: deploy

on:
  push:
    branches:
      - main

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${AWS_DNS}
          username: ${AWS_USER}
          key: ${SSH_PRIVATE_KEY}
          source: .
          target: ./docker-tutorial
