name: deploy

on:
  push:
    branches:
      - main

jobs:
  ec2_deploy:
    environment: Environment1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_DNS }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_PK }}
          source: .
          target: /home/${{ secrets.AWS_USER }}/docker-tutorial
          rm: true
      - name: run build and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_DNS }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_PK }}
          script: |
            cd /home/${{ secrets.AWS_USER }}/docker-tutorial
            docker build -t image1 .
            docker run -e NAME=${{ secrets.NAME }} image1
