name: deploy

on:
  push:
    branches:
      - main

jobs:
  Docker:
    environment: Environment1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}:latest


  ec2:
    environment: Environment1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/checkout@master
      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_DNS }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_PK }}
          source: ${{ GITHUB_WORKSPACE }}/
          target: /home/${{ secrets.AWS_USER }}/docker-tutorial
          rm: true
#      - name: run script
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.AWS_DNS }}
#          username: ${{ secrets.AWS_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#
