name: deploy

on:
  push:
    branches:
      - main

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_DNS }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: ./docker-tutorial
