name: deploy

on:
  push:
    branches:
      - main

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Test
        run: echo ${{ secrets.DOCKER_ID }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PAT }}
      -
        name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
